version: "3"
services:
  django_api:
    build:
      context: . 
      dockerfile: DockerfileDjango
    command: "manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    volumes:
      - "./API/.:/app/."
    ports:
      - 80:8000
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: sport
      MARIADB_PASSWORD: sport
    ports:
      - 3306:3306
  adminer:
    image: adminer
    depends_on:
      - database
    ports:
      - 8080:8080
